//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerSystem
    {
        public int computer_id { get; set; }
        public Nullable<int> storage_device_id { get; set; }
        public Nullable<int> graphics_card_id { get; set; }
        public Nullable<int> processor_id { get; set; }
        public Nullable<int> memory_id { get; set; }
        public string weight { get; set; }
        public string power_supply { get; set; }
        public string additional_notes { get; set; }
    
        public virtual GraphicsCard GraphicsCard { get; set; }
        public virtual Memory Memory { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual StorageDevice StorageDevice { get; set; }
    }
}
